language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t mayurbakale/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true mayurbakale/dockerreact npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-volume-prod"
  env: "DockerReactVolumeProd-env"
  bucket_name: "elasticbeanstalk-us-east-2-205502942541"
  bucket_path: "docker-react-volume-prod"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"