language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t mayurbakale/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true mayurbakale/dockerreact npm run test